version: "3.8"
services:
  fake-iot:
    build: ./fake_iot
    container_name: iot_fake
  server:
    build: ./server
    container_name: iot_server
    ports:
      - "5000:5000"
    volumes:
      - ./server/database.db:/app/database.db
  dashboard:
    build: ./dashboard
    container_name: iot_dashboard
    ports:
      - "8050:8050"
    depends_on:
      - server
